name: django_primer_designer_env
channels:
    - conda-forge
    - bioconda
dependencies:
    - pip
    - dicey
    - pypandoc
    - pandoc
    - samtools
    - pip:
        - django
        - requests
        - primer3-py
        - python-docx
        - python-decouple
