# Generated by Django 6.0.3 on 2026-03-31 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrimerSettingsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use_case",
                    models.CharField(
                        choices=[("PCR", "PCR"), ("qPCR", "qPCR")], max_length=10
                    ),
                ),
                ("tm", models.IntegerField()),
                ("gc", models.IntegerField()),
                ("max_poly_x", models.IntegerField()),
                ("productsize_range", models.JSONField()),
                ("reference_genome", models.CharField(max_length=50)),
                ("primer_size", models.IntegerField(blank=True, null=True)),
                ("target", models.JSONField(blank=True, null=True)),
                ("context", models.CharField(default="genomic", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="DesignResultsSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("variant_info_data", models.JSONField(blank=True, null=True)),
                ("primer_search_results", models.JSONField(blank=True, null=True)),
                (
                    "primer_settings",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="param_forwarding",
                        to="primer_designer_app.primersettingsmodel",
                    ),
                ),
            ],
        ),
    ]
